### ISSUE TITLE
missing dokan1.dll

### ISSUE THREAD

**Issue by the-liquid-metal** [antiufo/Shaman.Dokan.Archive#2]
found this error:

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: Unable to load DLL 'dokan1.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at DokanNet.Native.NativeMethods.DokanMain(DOKAN_OPTIONS& options, DOKAN_OPERATIONS& operations)
   at DokanNet.Dokan.Mount(IDokanOperations operations, String mountPoint, DokanOptions mountOptions, Int32 threadCount, Int32 version, TimeSpan timeout, String uncName, Int32 allocationUnitSize, Int32 sectorSize, ILogger logger)
   at Shaman.Dokan.FileSystemBase.<>c__DisplayClass58_0.<MountSimple>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at Shaman.Dokan.FileSystemBase.MountSimple(Int32 threadCount)
   at Shaman.Dokan.SevenZipProgram.Main(String[] args) in C:\Repositories\BuildFs\BuildFs\Shaman.Dokan.Archive\Program.cs:line 21

**Comment by dotnetCarpenter** [comment]
I got the same error.

I have installed [Dokany 1.3.1.1000](https://github.com/dokan-dev/dokany/releases/tag/v1.3.1.1000) and [Microsoft Visual C++ Redistributable for Visual Studio 2019](https://visualstudio.microsoft.com/downloads/).

```ps
PS C:\Users\jonro\Tools\Shaman.Dokan.Archive> .\Shaman.Dokan.Archive.exe ..\..\Downloads\foobar.rar --open
Mounted.
C:\DokanFs\SevenZipFs-..-..-Downloads-foobar.rar

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: Unable to load DLL 'dokan1.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at DokanNet.Native.NativeMethods.DokanMain(DOKAN_OPTIONS& options, DOKAN_OPERATIONS& operations)
   at DokanNet.Dokan.Mount(IDokanOperations operations, String mountPoint, DokanOptions mountOptions, Int32 threadCount, Int32 version, TimeSpan timeout, String uncName, Int32 allocationUnitSize, Int32 sectorSize, ILogger logger)
   at Shaman.Dokan.FileSystemBase.<>c__DisplayClass58_0.<MountSimple>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at Shaman.Dokan.FileSystemBase.MountSimple(Int32 threadCount)
   at Shaman.Dokan.SevenZipProgram.Main(String[] args)
```

@antiufo What version of Dokan /Dokany is supported?

**Comment by dotnetCarpenter** [comment]
`dokan1.dll` is located in _C:\Windows\System32\dokan1.dll_ on my system.

**Comment by dotnetCarpenter** [comment]
So I guess I am missing [DokanNet](https://www.nuget.org/packages/DokanNet), since this is a .NET project. 

But after [setting up NuGet](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/register-packagesource?view=powershell-7), I get the following:

```
Install-Package DokanNet
The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'NuGet'?
Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
Install-Package : Dependency loop detected for package 'DokanNet'.
At line:1 char:1
+ Install-Package DokanNet
+ ~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : Deadlock detected: (DokanNet:String) [Install-Package], Exception
   + FullyQualifiedErrorId : DependencyLoopDetected,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

And now I read that `dokan1.dll` is not even in DukanNet. https://github.com/dokan-dev/dokan-dotnet/issues/173

**Oh my - it is a mess!**

**Comment by painfull30** [comment]
+

**Comment by asheroto** [comment]
Looks like it's because Dokan is now on version 2.
