### ISSUE TITLE
Dokan Version Error (with Dokan 1.3.0.1000)

### ISSUE THREAD

**Issue by dvasdekis** [antiufo/Shaman.Dokan.Archive#3]
Hi! I've installed the latest version of Dokan to get this to work (1.3.0.1000), but I get the below error trying to run S.D.A from Powershell:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> DokanNet.DokanException: Version error
   at DokanNet.Dokan.Mount(IDokanOperations operations, String mountPoint, DokanOptions mountOptions, Int32 threadCount, Int32 version, TimeSpan timeout, String uncName, Int32 allocationUnitSize, Int32 sectorSize, ILogger logger)
   at Shaman.Dokan.FileSystemBase.<>c__DisplayClass58_0.<MountSimple>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at Shaman.Dokan.FileSystemBase.MountSimple(Int32 threadCount)
   at Shaman.Dokan.SevenZipProgram.Main(String[] args)
```
Am I right in thinking that this needs to be updated to work with the latest version of Dokan?

Thank you!!

**Comment by dvasdekis** [comment]
@meee1 Would you consider packaging your current version, given that it seems to fix this?

**Comment by the-liquid-metal** [comment]
the same error still occurs in Dokan v1.4.0.1000.

**Comment by cuixiping** [comment]
The same error still occurs in Dokan v1.2.2.1000 to v1.4.0.1000.

**Comment by fiddyschmitt** [comment]
Same. Using Dokan 1.4.0.1000 (x64)
